"""agregar valor antes de impuestos a cuentas

Revision ID: 705fba6c7e4f
Revises: e427d5e81915
Create Date: 2026-09-28 22:28:52.449944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705fba6c7e4f'
down_revision: Union[str, Sequence[str], None] = 'e427d5e81915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'taxable_amount')
    # ### end Alembic commands ###
