"""permitir pagos historicos por cuenta

Revision ID: e17f7a97b86d
Revises: 44e8195ee510
Create Date: 2026-09-29 00:22:17.502104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17f7a97b86d'
down_revision: Union[str, Sequence[str], None] = '44e8195ee510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payments_account_id_key'), 'payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('payments_account_id_key'), 'payments', ['account_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
